apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: krun-traffic-manager
  labels:
    app.kubernetes.io/name: krun-traffic-manager
    app.kubernetes.io/component: traffic-manager
    app.kubernetes.io/part-of: krun-debug-runtime
    app.kubernetes.io/managed-by: krun
    krun.ftechmax/runtime: "true"
  annotations:
    krun.ftechmax/component: traffic-runtime
subjects:
  - kind: ServiceAccount
    name: krun-traffic-manager
    namespace: krun-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: krun-traffic-manager
