apiVersion: v1
kind: Service
metadata:
  name: krun-traffic-manager
  namespace: krun-system
  labels:
    app.kubernetes.io/name: krun-traffic-manager
    app.kubernetes.io/component: traffic-manager
    app.kubernetes.io/part-of: krun-debug-runtime
    app.kubernetes.io/managed-by: krun
    krun.ftechmax/runtime: "true"
  annotations:
    krun.ftechmax/component: traffic-runtime
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: krun-traffic-manager
    app.kubernetes.io/component: traffic-manager
    app.kubernetes.io/part-of: krun-debug-runtime
  ports:
    - name: api
      port: 8080
      targetPort: api
      protocol: TCP
